# Generated by Django 4.2.19 on 2025-09-08 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='blue_value',
        ),
        migrations.RemoveField(
            model_name='color',
            name='green_value',
        ),
        migrations.RemoveField(
            model_name='color',
            name='red_value',
        ),
    ]
