# Generated by Django 4.2.19 on 2025-09-08 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_color_blue_value_remove_color_green_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='model_date',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
