# Generated by Django 4.2.19 on 2025-09-08 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_carmodel_model_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='img',
        ),
    ]
