# Generated by Django 4.2.19 on 2025-09-08 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisment',
            name='img',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
    ]
