# Generated by Django 4.2.19 on 2025-09-08 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisment', '0002_alter_advertisment_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisment',
            name='img',
        ),
    ]
