# Generated by Django 4.2.19 on 2025-09-08 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.TextField(blank=True, default='')),
                ('name', models.TextField(blank=True, default='', max_length=300)),
                ('mobile_phone', models.TextField(blank=True, default='')),
                ('payment_method', models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Bank-Financing', 'Bank-Financing')], max_length=20)),
                ('language', models.CharField(blank=True, choices=[('Arabic', 'Arabic'), ('English', 'English')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
